# Generated by Django 5.2.4 on 2025-09-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0023_make_credencial_hubsoft_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoServidorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para identificar esta configuração SMTP', max_length=200, verbose_name='Nome da Configuração')),
                ('servidor_smtp', models.CharField(help_text='Endereço do servidor SMTP (ex: smtp.gmail.com)', max_length=255, verbose_name='Servidor SMTP')),
                ('porta', models.IntegerField(default=587, help_text='Porta do servidor SMTP (587 para TLS, 465 para SSL, 25 para sem criptografia)', verbose_name='Porta SMTP')),
                ('usuario', models.CharField(help_text='Usuário para autenticação no servidor SMTP', max_length=255, verbose_name='Usuário')),
                ('senha', models.CharField(help_text='Senha para autenticação no servidor SMTP', max_length=255, verbose_name='Senha')),
                ('usar_tls', models.BooleanField(default=True, help_text='Habilita criptografia TLS', verbose_name='Usar TLS')),
                ('usar_ssl', models.BooleanField(default=False, help_text='Habilita criptografia SSL', verbose_name='Usar SSL')),
                ('email_remetente', models.EmailField(help_text='Email que aparecerá como remetente', max_length=254, verbose_name='Email do Remetente')),
                ('nome_remetente', models.CharField(blank=True, help_text='Nome que aparecerá como remetente', max_length=255, verbose_name='Nome do Remetente')),
                ('timeout', models.PositiveIntegerField(default=30, help_text='Tempo limite para conexão SMTP', verbose_name='Timeout (segundos)')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta configuração está ativa', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_ultimo_teste', models.DateTimeField(blank=True, help_text='Data do último teste de conexão bem-sucedido', null=True, verbose_name='Data do Último Teste')),
                ('resultado_ultimo_teste', models.TextField(blank=True, help_text='Resultado detalhado do último teste de conexão', verbose_name='Resultado do Último Teste')),
            ],
            options={
                'verbose_name': 'Configuração do Servidor de Email',
                'verbose_name_plural': 'Configurações dos Servidores de Email',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo do template de email', max_length=200, verbose_name='Nome do Template')),
                ('tipo', models.CharField(choices=[('marketing', 'Marketing'), ('cobranca', 'Cobrança'), ('informativo', 'Informativo'), ('promocional', 'Promocional'), ('lembrete', 'Lembrete'), ('confirmacao', 'Confirmação'), ('outro', 'Outro')], default='informativo', help_text='Categoria do template de email', max_length=20, verbose_name='Tipo do Template')),
                ('assunto', models.CharField(help_text='Assunto do email. Suporta variáveis: {{nome_cliente}}, {{valor_fatura}}, etc.', max_length=255, verbose_name='Assunto do Email')),
                ('corpo_html', models.TextField(help_text='Conteúdo HTML do email. Suporta variáveis como {{nome_cliente}}, {{telefone}}, {{dados_dinamicos.endereco}}, etc.', verbose_name='Corpo do Email (HTML)')),
                ('corpo_texto', models.TextField(blank=True, help_text='Versão em texto puro do email (opcional). Suporta as mesmas variáveis do HTML.', verbose_name='Corpo do Email (Texto Puro)')),
                ('css_personalizado', models.TextField(blank=True, help_text='CSS adicional para estilização do email', verbose_name='CSS Personalizado')),
                ('variaveis_personalizadas', models.JSONField(blank=True, default=dict, help_text="Variáveis adicionais específicas deste template em formato: {'var_name': 'valor_padrao'}", verbose_name='Variáveis Personalizadas')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do template e seu uso', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Se este template está ativo', verbose_name='Ativo')),
                ('total_enviados', models.PositiveIntegerField(default=0, verbose_name='Total de Emails Enviados')),
                ('total_sucessos', models.PositiveIntegerField(default=0, verbose_name='Total de Sucessos')),
                ('total_erros', models.PositiveIntegerField(default=0, verbose_name='Total de Erros')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_ultimo_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Último Envio')),
            ],
            options={
                'verbose_name': 'Template de Email',
                'verbose_name_plural': 'Templates de Email',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CampanhaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo da campanha de email', max_length=255, verbose_name='Nome da Campanha')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da campanha', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('executando', 'Executando'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='rascunho', max_length=20, verbose_name='Status da Campanha')),
                ('tipo_agendamento', models.CharField(choices=[('unico', 'Envio Único'), ('diario', 'Diário'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('personalizado', 'Personalizado (Cron)')], default='unico', max_length=20, verbose_name='Tipo de Agendamento')),
                ('data_agendamento', models.DateTimeField(blank=True, help_text='Data e hora para execução (para envio único ou primeira execução)', null=True, verbose_name='Data de Agendamento')),
                ('expressao_cron', models.CharField(blank=True, help_text="Expressão cron para agendamento personalizado (ex: '0 9 * * 1' = toda segunda às 9h)", max_length=100, verbose_name='Expressão Cron')),
                ('intervalo_recorrencia', models.PositiveIntegerField(default=1, help_text='Intervalo para repetição (ex: 1 = todo dia, 2 = dia sim/dia não)', verbose_name='Intervalo de Recorrência')),
                ('data_fim_recorrencia', models.DateTimeField(blank=True, help_text='Data limite para parar a recorrência (opcional)', null=True, verbose_name='Data Fim da Recorrência')),
                ('limite_envios_por_execucao', models.PositiveIntegerField(default=0, help_text='0 = sem limite. Útil para evitar sobrecarga do servidor', verbose_name='Limite de Envios por Execução')),
                ('intervalo_entre_envios', models.PositiveIntegerField(default=0, help_text='Pausa entre cada envio individual. 0 = sem pausa', verbose_name='Intervalo Entre Envios (segundos)')),
                ('filtros_sql_adicionais', models.TextField(blank=True, help_text='Cláusulas WHERE adicionais para filtrar os resultados', verbose_name='Filtros SQL Adicionais')),
                ('total_destinatarios', models.PositiveIntegerField(default=0, verbose_name='Total de Destinatários')),
                ('total_enviados', models.PositiveIntegerField(default=0, verbose_name='Total Enviados')),
                ('total_sucessos', models.PositiveIntegerField(default=0, verbose_name='Total de Sucessos')),
                ('total_erros', models.PositiveIntegerField(default=0, verbose_name='Total de Erros')),
                ('total_pendentes', models.PositiveIntegerField(default=0, verbose_name='Total Pendentes')),
                ('ativo', models.BooleanField(default=True, help_text='Se a campanha está ativa', verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_inicio_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início da Execução')),
                ('data_fim_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim da Execução')),
                ('proxima_execucao', models.DateTimeField(blank=True, help_text='Data da próxima execução agendada', null=True, verbose_name='Próxima Execução')),
                ('log_execucao', models.TextField(blank=True, help_text='Log detalhado das execuções', verbose_name='Log de Execução')),
                ('consulta_execucao', models.ForeignKey(blank=True, help_text='Execução específica da consulta SQL', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.consultaexecucao', verbose_name='Execução da Consulta')),
                ('template_sql', models.ForeignKey(blank=True, help_text='Template SQL para buscar os dados dos clientes', null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.templatesql', verbose_name='Template SQL')),
                ('configuracao_servidor', models.ForeignKey(help_text='Configuração SMTP para envio dos emails', on_delete=django.db.models.deletion.CASCADE, to='emails.configuracaoservidoremail', verbose_name='Configuração do Servidor')),
                ('template_email', models.ForeignKey(help_text='Template que será usado para os emails', on_delete=django.db.models.deletion.CASCADE, to='emails.templateemail', verbose_name='Template de Email')),
            ],
            options={
                'verbose_name': 'Campanha de Email',
                'verbose_name_plural': 'Campanhas de Email',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EnvioEmailIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinatario', models.EmailField(help_text='Email para onde foi enviado', max_length=254, verbose_name='Email do Destinatário')),
                ('nome_destinatario', models.CharField(help_text='Nome do destinatário', max_length=255, verbose_name='Nome do Destinatário')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('assunto_enviado', models.CharField(help_text='Assunto do email após processamento das variáveis', max_length=255, verbose_name='Assunto Enviado')),
                ('corpo_enviado', models.TextField(help_text='Corpo do email após processamento das variáveis', verbose_name='Corpo Enviado')),
                ('variaveis_utilizadas', models.JSONField(blank=True, default=dict, help_text='Variáveis que foram utilizadas no envio', verbose_name='Variáveis Utilizadas')),
                ('anexos_enviados', models.JSONField(blank=True, default=list, help_text='Lista de anexos que foram enviados', verbose_name='Anexos Enviados')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas de Envio')),
                ('data_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Agendamento')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data do Envio')),
                ('tempo_envio_ms', models.PositiveIntegerField(blank=True, help_text='Tempo gasto para enviar o email em milissegundos', null=True, verbose_name='Tempo de Envio (ms)')),
                ('resposta_servidor', models.TextField(blank=True, help_text='Resposta do servidor SMTP', verbose_name='Resposta do Servidor')),
                ('erro_detalhado', models.TextField(blank=True, help_text='Detalhes do erro caso ocorra', verbose_name='Erro Detalhado')),
                ('message_id', models.CharField(blank=True, help_text='ID da mensagem retornado pelo servidor', max_length=255, verbose_name='Message ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_individuais', to='emails.campanhaemail', verbose_name='Campanha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.clienteconsultado', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Envio de Email Individual',
                'verbose_name_plural': 'Envios de Email Individuais',
                'ordering': ['-data_envio'],
                'unique_together': {('campanha', 'cliente', 'email_destinatario')},
            },
        ),
        migrations.CreateModel(
            name='LogEnvioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Nível do Log')),
                ('acao', models.CharField(help_text='Ação que foi executada', max_length=100, verbose_name='Ação')),
                ('mensagem', models.TextField(help_text='Descrição detalhada da ação', verbose_name='Mensagem')),
                ('dados_extras', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em formato JSON', verbose_name='Dados Extras')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.campanhaemail', verbose_name='Campanha')),
                ('envio_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.envioemailindividual', verbose_name='Envio Individual')),
            ],
            options={
                'verbose_name': 'Log de Envio de Email',
                'verbose_name_plural': 'Logs de Envio de Email',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
