# Generated by Django 5.2.4 on 2025-09-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0023_make_credencial_hubsoft_optional'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhaemail',
            name='credencial_banco',
            field=models.ForeignKey(blank=True, help_text='Credencial para conexão com banco de dados', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.credenciaisbancodados', verbose_name='Credencial do Banco'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='credencial_hubsoft',
            field=models.ForeignKey(blank=True, help_text='Credencial para consulta na API (obrigatório se não pular API)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.credenciaishubsoft', verbose_name='Credencial Hubsoft'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='pular_consulta_api',
            field=models.BooleanField(default=False, help_text='Se marcado, não consultará dados na API Hubsoft. Usará apenas dados do SQL.', verbose_name='Pular Consulta na API'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='valores_variaveis_sql',
            field=models.JSONField(blank=True, default=dict, help_text='Valores das variáveis necessárias para executar o template SQL', null=True, verbose_name='Valores das Variáveis SQL'),
        ),
    ]
