# Generated by Django 5.2.4 on 2025-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_add_sql_variables_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanhaemail',
            name='ativa_recorrencia',
            field=models.BooleanField(default=True, help_text='Se a recorrência está ativa (pode ser pausada temporariamente)', verbose_name='Recorrência Ativa'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='dia_mes_recorrencia',
            field=models.PositiveIntegerField(blank=True, help_text='Dia do mês para execução mensal (1-31)', null=True, verbose_name='Dia do Mês'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='dias_semana_recorrencia',
            field=models.CharField(blank=True, help_text="Dias da semana para execução semanal (ex: '1,3,5' = seg, qua, sex)", max_length=50, verbose_name='Dias da Semana'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='hora_execucao',
            field=models.TimeField(blank=True, help_text='Hora específica para execução recorrente', null=True, verbose_name='Hora de Execução'),
        ),
        migrations.AlterField(
            model_name='campanhaemail',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('processando', 'Processando Dados'), ('agendada', 'Agendada'), ('executando', 'Executando'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('erro', 'Erro')], default='rascunho', max_length=20, verbose_name='Status da Campanha'),
        ),
    ]
