# Generated by Django 5.2.9 on 2026-01-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0023_make_credencial_hubsoft_optional'),
        ('emails', '0003_campanhaemail_ativa_recorrencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para identificar esta base de leads', max_length=255, verbose_name='Nome da Base')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da base de leads', verbose_name='Descrição')),
                ('arquivo_original_nome', models.CharField(help_text='Nome do arquivo CSV original que foi importado', max_length=255, verbose_name='Nome do Arquivo Original')),
                ('total_leads', models.PositiveIntegerField(default=0, help_text='Total de leads importados do CSV', verbose_name='Total de Leads')),
                ('total_validos', models.PositiveIntegerField(default=0, help_text='Total de leads com email válido', verbose_name='Total de Leads Válidos')),
                ('total_invalidos', models.PositiveIntegerField(default=0, help_text='Total de leads com email inválido ou duplicado', verbose_name='Total de Leads Inválidos')),
                ('colunas_disponiveis', models.JSONField(default=list, help_text="Lista de todas as colunas detectadas no CSV (ex: ['Nome', 'Email', 'Telefone', 'Local'])", verbose_name='Colunas Disponíveis')),
                ('coluna_email', models.CharField(help_text='Nome da coluna que contém o email', max_length=100, verbose_name='Coluna de Email')),
                ('coluna_nome', models.CharField(help_text='Nome da coluna que contém o nome', max_length=100, verbose_name='Coluna de Nome')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('ativo', models.BooleanField(default=True, help_text='Se esta base de leads está ativa', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Base de Leads',
                'verbose_name_plural': 'Bases de Leads',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='envioemailindividual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='tipo_fonte',
            field=models.CharField(choices=[('clientes', 'Clientes'), ('leads', 'Leads (CSV)')], default='clientes', help_text='Fonte dos dados para a campanha: Clientes (SQL/Execução) ou Leads (CSV)', max_length=20, verbose_name='Tipo de Fonte'),
        ),
        migrations.AlterField(
            model_name='envioemailindividual',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.clienteconsultado', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='campanhaemail',
            name='base_leads',
            field=models.ForeignKey(blank=True, help_text='Base de leads importada via CSV', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.baseleads', verbose_name='Base de Leads'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email do lead', max_length=254, verbose_name='Email')),
                ('nome', models.CharField(help_text='Nome do lead', max_length=255, verbose_name='Nome')),
                ('dados_adicionais', models.JSONField(blank=True, default=dict, help_text="Dados adicionais do CSV em formato dicionário (ex: {'Telefone': 'xxx', 'Local': 'yyy'})", verbose_name='Dados Adicionais')),
                ('linha_original', models.PositiveIntegerField(help_text='Número da linha no CSV original (começando em 1)', verbose_name='Linha Original')),
                ('valido', models.BooleanField(default=True, help_text='Se este lead é válido para envio', verbose_name='Válido')),
                ('motivo_invalido', models.TextField(blank=True, help_text='Motivo pelo qual o lead foi marcado como inválido', verbose_name='Motivo Inválido')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('base_leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='emails.baseleads', verbose_name='Base de Leads')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['linha_original'],
            },
        ),
        migrations.AddField(
            model_name='envioemailindividual',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.lead', verbose_name='Lead'),
        ),
        migrations.AddConstraint(
            model_name='envioemailindividual',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', False), ('lead__isnull', True)), models.Q(('cliente__isnull', True), ('lead__isnull', False)), _connector='OR'), name='cliente_ou_lead'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('base_leads', 'email')},
        ),
    ]
