# Generated by Django 5.2.9 on 2026-01-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_baseleads_alter_envioemailindividual_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseleads',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='baseleads',
            name='delimitador_usado',
            field=models.CharField(default=';', help_text='Delimitador usado no CSV (;, ,, tab)', max_length=5, verbose_name='Delimitador'),
        ),
        migrations.AddField(
            model_name='baseleads',
            name='encoding_usado',
            field=models.CharField(default='utf-8', help_text='Encoding do arquivo CSV', max_length=20, verbose_name='Encoding'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='arquivo_original_nome',
            field=models.CharField(help_text='Nome do arquivo CSV que foi importado', max_length=255, verbose_name='Nome do Arquivo Original'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se esta base está ativa para uso', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='coluna_nome',
            field=models.CharField(help_text='Nome da coluna que contém o nome do lead', max_length=100, verbose_name='Coluna de Nome'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='colunas_disponiveis',
            field=models.JSONField(default=list, help_text='Lista de todas as colunas encontradas no CSV', verbose_name='Colunas Disponíveis'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada sobre esta base de leads', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='total_invalidos',
            field=models.PositiveIntegerField(default=0, help_text='Leads com email inválido ou dados faltando', verbose_name='Total de Inválidos'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='total_leads',
            field=models.PositiveIntegerField(default=0, help_text='Total de linhas processadas do CSV', verbose_name='Total de Leads'),
        ),
        migrations.AlterField(
            model_name='baseleads',
            name='total_validos',
            field=models.PositiveIntegerField(default=0, help_text='Leads com email válido', verbose_name='Total de Válidos'),
        ),
        migrations.AlterField(
            model_name='campanhaemail',
            name='base_leads',
            field=models.ForeignKey(blank=True, help_text="Base de leads importada (apenas para tipo_fonte='leads')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.baseleads', verbose_name='Base de Leads'),
        ),
        migrations.AlterField(
            model_name='campanhaemail',
            name='proxima_execucao',
            field=models.DateTimeField(blank=True, help_text='Data e hora da próxima execução programada', null=True, verbose_name='Próxima Execução'),
        ),
        migrations.AlterField(
            model_name='campanhaemail',
            name='tipo_fonte',
            field=models.CharField(choices=[('clientes', 'Clientes (SQL/Execução)'), ('leads', 'Leads (CSV Importado)')], default='clientes', help_text='De onde vêm os dados: clientes do sistema ou leads importados', max_length=20, verbose_name='Tipo de Fonte'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='dados_adicionais',
            field=models.JSONField(default=dict, help_text='Todas as outras colunas do CSV (Telefone, Local, etc.)', verbose_name='Dados Adicionais'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='linha_original',
            field=models.PositiveIntegerField(help_text='Número da linha no CSV original', verbose_name='Linha Original'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='motivo_invalido',
            field=models.TextField(blank=True, help_text='Razão pela qual o lead foi marcado como inválido', verbose_name='Motivo Inválido'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='valido',
            field=models.BooleanField(default=True, help_text='Se o lead tem dados válidos (email principalmente)', verbose_name='Válido'),
        ),
    ]
