# Generated by Django 4.2.27 on 2025-12-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 2 dias vencidos Mega', max_length=200, verbose_name='Nome da Campanha')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da campanha', verbose_name='Descrição')),
                ('campaign_id', models.IntegerField(help_text='ID da campanha no sistema Native', verbose_name='ID da Campanha Native')),
                ('template_sql_id', models.IntegerField(help_text='ID do template SQL a ser usado', verbose_name='ID do Template SQL')),
                ('credencial_banco_id', models.IntegerField(help_text='ID da credencial do banco de dados', verbose_name='ID da Credencial do Banco')),
                ('credencial_hubsoft_id', models.IntegerField(blank=True, help_text='ID da credencial Hubsoft (opcional se pular_consulta_api = True)', null=True, verbose_name='ID da Credencial Hubsoft')),
                ('valores_variaveis', models.JSONField(default=dict, help_text='Variáveis dinâmicas em formato JSON. Ex: {"dia1": "2", "dia2": "2"}', verbose_name='Variáveis')),
                ('pular_consulta_api', models.BooleanField(default=False, help_text='Se True, não consulta a API Hubsoft', verbose_name='Pular Consulta API')),
                ('enabled', models.BooleanField(default=True, help_text='Campanha ativa e disponível para execução', verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Execução')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execucao_id', models.IntegerField(blank=True, help_text='ID da execução criada na API', null=True, verbose_name='ID da Execução')),
                ('lista_id', models.IntegerField(blank=True, help_text='ID da lista criada no Native', null=True, verbose_name='ID da Lista')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em Execução'), ('monitoring', 'Monitorando'), ('creating_list', 'Criando Lista'), ('updating_campaign', 'Atualizando Campanha'), ('completed', 'Concluída'), ('failed', 'Falhou'), ('timeout', 'Timeout')], default='pending', max_length=20, verbose_name='Status')),
                ('total_records', models.IntegerField(default=0, help_text='Número de registros processados', verbose_name='Total de Registros')),
                ('success', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('error_message', models.TextField(blank=True, help_text='Detalhes do erro, se houver', verbose_name='Mensagem de Erro')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='campaigns.campaign', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('level', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro')], default='INFO', max_length=10, verbose_name='Nível')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.execution', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Log de Execução',
                'verbose_name_plural': 'Logs de Execução',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['enabled', '-last_executed_at'], name='campaigns_c_enabled_52093b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_id'], name='campaigns_c_campaig_8ed7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['execution', 'timestamp'], name='campaigns_e_executi_d1dfa5_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['-started_at'], name='campaigns_e_started_140cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['status'], name='campaigns_e_status_30ce3c_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['campaign', '-started_at'], name='campaigns_e_campaig_4aae79_idx'),
        ),
    ]
