# Generated by Django 5.2.9 on 2026-01-09 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único do tipo', max_length=100, unique=True)),
                ('nome', models.CharField(help_text='Nome descritivo do tipo', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('categoria', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('native', 'Ligações Native'), ('sistema', 'Sistema')], default='sistema', max_length=50)),
                ('icone', models.CharField(default='bell', help_text='Nome do ícone Lucide', max_length=50)),
                ('cor', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarelo'), ('danger', 'Vermelho'), ('info', 'Ciano')], default='primary', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Notificação',
                'verbose_name_plural': 'Tipos de Notificações',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('icone', models.CharField(default='bell', max_length=50)),
                ('cor', models.CharField(default='primary', max_length=20)),
                ('url', models.CharField(blank=True, help_text='URL para onde a notificação aponta', max_length=500)),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados adicionais em JSON', null=True)),
                ('content_type', models.CharField(blank=True, help_text='Tipo de objeto relacionado', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID do objeto relacionado', null=True)),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Data de expiração da notificação', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanha_manager.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', '-data_criacao'], name='campanha_ma_usuario_4e7c93_idx'), models.Index(fields=['usuario', 'lida'], name='campanha_ma_usuario_6e405c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Se este tipo de notificação está ativo para o usuário')),
                ('enviar_email', models.BooleanField(default=False, help_text='Enviar também por email')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_notificacao', to=settings.AUTH_USER_MODEL)),
                ('tipo_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha_manager.tiponotificacao')),
            ],
            options={
                'verbose_name': 'Configuração de Notificação',
                'verbose_name_plural': 'Configurações de Notificações',
                'unique_together': {('usuario', 'tipo_notificacao')},
            },
        ),
    ]
