# Generated by Django 5.2.4 on 2025-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0015_enviohsmindividual_template_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviohsmindividual',
            name='dados_pagamento',
            field=models.JSONField(blank=True, default=dict, help_text='Dados específicos do pagamento (hsm_parametros)', verbose_name='Dados de Pagamento'),
        ),
        migrations.AddField(
            model_name='enviohsmindividual',
            name='url_file',
            field=models.URLField(blank=True, help_text='Link do boleto PDF', verbose_name='URL do Arquivo'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='cnpj_empresa',
            field=models.CharField(blank=True, help_text='CNPJ da empresa sem formatação para PIX (pix.chave)', max_length=18, verbose_name='CNPJ da Empresa'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='configuracao_pagamento',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para envio de HSM com pagamento', verbose_name='Configuração de Pagamento'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='nome_produto_padrao',
            field=models.CharField(blank=True, help_text="Nome padrão do produto (ex: 'Fatura NomeDaEmpresa')", max_length=255, verbose_name='Nome do Produto Padrão'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='razao_social_empresa',
            field=models.CharField(blank=True, help_text='Razão social para PIX (pix.nom_empresa)', max_length=255, verbose_name='Razão Social da Empresa'),
        ),
        migrations.AddField(
            model_name='hsmtemplate',
            name='tipo_template',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('pagamento', 'Pagamento')], default='padrao', help_text='Define se é um template padrão ou de pagamento', max_length=20, verbose_name='Tipo de Template'),
        ),
    ]
