# Generated by Django 5.2.4 on 2025-08-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0016_enviohsmindividual_dados_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enviohsmindividual',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enviohsmindividual',
            name='envio_relacionado',
            field=models.ForeignKey(blank=True, help_text='Vincula os dois envios do mesmo cliente (primeiro e segundo HSM)', null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.enviohsmindividual', verbose_name='Envio Relacionado'),
        ),
        migrations.AddField(
            model_name='enviohsmindividual',
            name='hsm_enviado',
            field=models.CharField(choices=[('primeiro', 'Primeiro HSM'), ('segundo', 'Segundo HSM')], default='primeiro', help_text='Indica se este envio é do primeiro ou segundo HSM', max_length=20, verbose_name='HSM Enviado'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='cnpj_empresa_segundo',
            field=models.CharField(blank=True, help_text='CNPJ da empresa para PIX do segundo HSM (caso seja pagamento)', max_length=18, verbose_name='CNPJ da Empresa - Segundo HSM'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='configuracao_pagamento_segundo',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para envio de HSM de pagamento (segundo HSM)', verbose_name='Configuração de Pagamento - Segundo HSM'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='configuracao_variaveis_segundo',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento das variáveis do segundo HSM com campos dos dados', verbose_name='Configuração das Variáveis - Segundo HSM'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='habilitar_segundo_hsm',
            field=models.BooleanField(default=False, help_text='Ativa o envio de um segundo HSM após o primeiro', verbose_name='Habilitar Segundo HSM'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='hsm_template_segundo',
            field=models.ForeignKey(blank=True, help_text='Template HSM que será enviado como segundo HSM', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_segundo', to='campanhas.hsmtemplate', verbose_name='Template HSM Segundo'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='intervalo_segundo_hsm',
            field=models.PositiveIntegerField(default=3, help_text='Tempo em segundos para aguardar antes de enviar o segundo HSM', verbose_name='Intervalo para Segundo HSM (segundos)'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='nome_produto_padrao_segundo',
            field=models.CharField(blank=True, help_text='Nome padrão do produto para o segundo HSM', max_length=255, verbose_name='Nome do Produto Padrão - Segundo HSM'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='razao_social_empresa_segundo',
            field=models.CharField(blank=True, help_text='Razão social para PIX do segundo HSM (caso seja pagamento)', max_length=255, verbose_name='Razão Social da Empresa - Segundo HSM'),
        ),
        migrations.AlterUniqueTogether(
            name='enviohsmindividual',
            unique_together={('envio_matrix', 'cliente', 'hsm_enviado')},
        ),
    ]
