# Generated by Django 5.2.4 on 2025-08-19 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0017_alter_enviohsmindividual_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamentoHSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome descritivo para identificar esta configuração', max_length=200, verbose_name='Nome da Configuração')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da configuração', verbose_name='Descrição')),
                ('razao_social_empresa', models.CharField(help_text='Razão social para PIX (pix.nom_empresa)', max_length=255, verbose_name='Razão Social da Empresa')),
                ('cnpj_empresa', models.CharField(help_text='CNPJ da empresa sem formatação para PIX (pix.chave)', max_length=18, verbose_name='CNPJ da Empresa')),
                ('nome_produto_padrao', models.CharField(help_text="Nome padrão do produto (ex: 'Fatura Mensal')", max_length=255, verbose_name='Nome do Produto Padrão')),
                ('tipo_produto', models.CharField(choices=[('digital-goods', 'Bens Digitais'), ('physical-goods', 'Bens Físicos'), ('services', 'Serviços')], default='digital-goods', max_length=50, verbose_name='Tipo de Produto')),
                ('val_imposto', models.DecimalField(decimal_places=2, default=0, help_text='Valor padrão do imposto', max_digits=10, verbose_name='Valor do Imposto')),
                ('val_desconto', models.DecimalField(decimal_places=2, default=0, help_text='Valor padrão do desconto', max_digits=10, verbose_name='Valor do Desconto')),
                ('variaveis_flow_padrao', models.JSONField(blank=True, default=dict, help_text='Variáveis adicionais que serão enviadas para o flow', verbose_name='Variáveis Padrão do Flow')),
                ('configuracao_extra', models.JSONField(blank=True, default=dict, help_text='Configurações adicionais em formato JSON', verbose_name='Configurações Extras')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Pagamento HSM',
                'verbose_name_plural': 'Configurações de Pagamento HSM',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='enviohsmmatrix',
            name='configuracao_pagamento',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações específicas para envio de HSM com pagamento (usado quando não há configuração selecionada)', verbose_name='Configuração de Pagamento Manual'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='configuracao_pagamento_hsm',
            field=models.ForeignKey(blank=True, help_text='Configuração reutilizável para dados de pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.configuracaopagamentohsm', verbose_name='Configuração de Pagamento'),
        ),
    ]
