# Generated by Django 5.2.4 on 2025-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0018_configuracaopagamentohsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviohsmindividual',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se este envio individual está ativo', verbose_name='Ativo'),
        ),
    ]
