# Generated by Django 5.2.4 on 2025-08-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0019_enviohsmindividual_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviohsmindividual',
            name='flow_variaveis_enviadas',
            field=models.JSONField(blank=True, default=dict, help_text='Variáveis que foram enviadas para o flow no momento do envio', verbose_name='Variáveis do Flow Enviadas'),
        ),
    ]
