# Generated by Django 5.2.4 on 2025-08-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0020_enviohsmindividual_flow_variaveis_enviadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteconsultado',
            name='dados_dinamicos',
            field=models.JSONField(blank=True, default=dict, help_text='Dados adicionais do cliente que podem ser usados em HSM e Flow', null=True, verbose_name='Dados Dinâmicos'),
        ),
    ]
