# Generated by Django 5.2.4 on 2025-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0021_add_dados_dinamicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaexecucao',
            name='pular_consulta_api',
            field=models.BooleanField(default=False, help_text='Se marcado, não consultará dados financeiros na API. Útil para campanhas que usam apenas dados do SQL.', verbose_name='Pular Consulta na API'),
        ),
    ]
