# Generated by Django 5.2.4 on 2025-08-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0022_add_pular_consulta_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaexecucao',
            name='credencial_hubsoft',
            field=models.ForeignKey(blank=True, help_text="Obrigatório apenas se 'Pular Consulta na API' estiver desmarcado", null=True, on_delete=django.db.models.deletion.CASCADE, to='campanhas.credenciaishubsoft', verbose_name='Credencial Hubsoft'),
        ),
    ]
