# Generated by Django 5.2.9 on 2026-01-09 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0023_make_credencial_hubsoft_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='Data')),
                ('hora', models.IntegerField(blank=True, null=True, verbose_name='Hora (0-23)')),
                ('endpoint', models.CharField(db_index=True, max_length=500, verbose_name='Endpoint')),
                ('metodo', models.CharField(max_length=10, verbose_name='Método HTTP')),
                ('total_requisicoes', models.IntegerField(default=0, verbose_name='Total de Requisições')),
                ('total_sucesso', models.IntegerField(default=0, verbose_name='Total de Sucessos')),
                ('total_erro_cliente', models.IntegerField(default=0, verbose_name='Total de Erros do Cliente')),
                ('total_erro_servidor', models.IntegerField(default=0, verbose_name='Total de Erros do Servidor')),
                ('tempo_medio_processamento', models.FloatField(blank=True, null=True, verbose_name='Tempo Médio (segundos)')),
                ('tempo_minimo_processamento', models.FloatField(blank=True, null=True, verbose_name='Tempo Mínimo (segundos)')),
                ('tempo_maximo_processamento', models.FloatField(blank=True, null=True, verbose_name='Tempo Máximo (segundos)')),
                ('usuarios_unicos', models.IntegerField(default=0, verbose_name='Usuários Únicos')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estatística de API',
                'verbose_name_plural': 'Estatísticas de API',
                'ordering': ['-data', '-hora'],
                'indexes': [models.Index(fields=['-data', 'endpoint'], name='campanhas_a_data_1bfc26_idx'), models.Index(fields=['-data', '-hora'], name='campanhas_a_data_f7d0c3_idx')],
                'unique_together': {('data', 'hora', 'endpoint', 'metodo')},
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_anonimo', models.BooleanField(default=False, verbose_name='Usuário Anônimo')),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], max_length=10, verbose_name='Método HTTP')),
                ('endpoint', models.CharField(db_index=True, max_length=500, verbose_name='Endpoint')),
                ('path_completo', models.TextField(verbose_name='Path Completo com Query Params')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('query_params', models.JSONField(blank=True, null=True, verbose_name='Query Parameters')),
                ('request_body', models.JSONField(blank=True, null=True, verbose_name='Request Body')),
                ('request_headers', models.JSONField(blank=True, null=True, verbose_name='Request Headers')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='Status Code HTTP')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro_cliente', 'Erro do Cliente (4xx)'), ('erro_servidor', 'Erro do Servidor (5xx)'), ('timeout', 'Timeout')], db_index=True, max_length=20, verbose_name='Status')),
                ('response_body', models.JSONField(blank=True, null=True, verbose_name='Response Body')),
                ('response_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho da Resposta (bytes)')),
                ('erro_tipo', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Tipo de Erro')),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('erro_traceback', models.TextField(blank=True, verbose_name='Traceback do Erro')),
                ('tempo_processamento', models.FloatField(blank=True, null=True, verbose_name='Tempo de Processamento (segundos)')),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('ambiente', models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('homologacao', 'Homologação'), ('producao', 'Produção')], default='producao', max_length=20, verbose_name='Ambiente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de API',
                'verbose_name_plural': 'Logs de API',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora', 'status'], name='campanhas_a_data_ho_70d843_idx'), models.Index(fields=['usuario', '-data_hora'], name='campanhas_a_usuario_6aa963_idx'), models.Index(fields=['endpoint', '-data_hora'], name='campanhas_a_endpoin_49d955_idx'), models.Index(fields=['status_code', '-data_hora'], name='campanhas_a_status__d5ff60_idx')],
            },
        ),
    ]
