# Generated by Django 5.2.9 on 2026-01-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0024_apilogestatistica_apilog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credenciaisbancodados',
            name='tipo_banco',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('clickhouse', 'ClickHouse')], max_length=20, verbose_name='Tipo de Banco'),
        ),
    ]
