# Generated by Django 5.2.9 on 2026-02-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0025_alter_credenciaisbancodados_tipo_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='arquivo_midia',
            field=models.FileField(blank=True, help_text='Upload de imagem ou arquivo para envio com HSM (será acessível via URL)', null=True, upload_to='hsm_midias/%Y/%m/%d/', verbose_name='Arquivo de Mídia'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='enviar_com_midia',
            field=models.BooleanField(default=False, help_text='Marque para enviar HSM com imagem ou arquivo anexado', verbose_name='Enviar com Mídia'),
        ),
        migrations.AddField(
            model_name='enviohsmmatrix',
            name='url_midia',
            field=models.URLField(blank=True, help_text="URL externa da mídia (alternativa ao upload de arquivo). Usada quando 'Enviar com Mídia' está marcado.", verbose_name='URL da Mídia'),
        ),
        migrations.AlterField(
            model_name='enviohsmindividual',
            name='url_file',
            field=models.URLField(blank=True, help_text='Link do arquivo/mídia (boleto PDF, imagem, etc.) enviado com o HSM', verbose_name='URL do Arquivo'),
        ),
    ]
